// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9Q0fNd1tRAsnl3x8xO-eX954g46zPDs4',
    appId: '1:12852964020:android:db40f316348cb6bc48c5e1',
    messagingSenderId: '12852964020',
    projectId: 'project-coati',
    storageBucket: 'project-coati.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiWzod6AxyDTlXwIPiERblRJEw0HuPozg',
    appId: '1:12852964020:ios:c8dbd9fd1e621b7648c5e1',
    messagingSenderId: '12852964020',
    projectId: 'project-coati',
    storageBucket: 'project-coati.appspot.com',
    iosClientId: '12852964020-abtttmtotn7o96r97h4eo0hk8fjmg9h6.apps.googleusercontent.com',
    iosBundleId: 'com.koaty.coati',
  );
}
