import 'package:flutter/material.dart';

class MyTheme {
  static ThemeData define(ColorScheme colorScheme) {
    return ThemeData(
      colorScheme: ColorScheme(
        brightness: colorScheme.brightness,
        primary: colorScheme.primary,
        onPrimary: colorScheme.onPrimary,
        primaryContainer: colorScheme.primaryContainer,
        onPrimaryContainer: colorScheme.onPrimaryContainer,
        secondary: colorScheme.secondary,
        onSecondary: colorScheme.onSecondary,
        secondaryContainer: colorScheme.secondaryContainer,
        onSecondaryContainer: colorScheme.onSecondaryContainer,
        tertiary: colorScheme.tertiary,
        onTertiary: colorScheme.onTertiary,
        tertiaryContainer: colorScheme.tertiaryContainer,
        onTertiaryContainer: colorScheme.onTertiaryContainer,
        error: colorScheme.error,
        errorContainer: colorScheme.errorContainer,
        onError: colorScheme.onError,
        onErrorContainer: colorScheme.onErrorContainer,
        background: colorScheme.background,
        onBackground: colorScheme.onBackground,
        surface: colorScheme.surface,
        onSurface: colorScheme.onSurface,
        surfaceVariant: colorScheme.surfaceVariant,
        onSurfaceVariant: colorScheme.onSurfaceVariant,
        outline: colorScheme.outline,
        onInverseSurface: colorScheme.onInverseSurface,
        inverseSurface: colorScheme.inverseSurface,
        inversePrimary: colorScheme.inversePrimary,
        shadow: colorScheme.shadow,
      ),
      useMaterial3: true,
      backgroundColor: const Color(0xFFFBFDF9),
      primaryColor: colorScheme.primary,
      splashColor: colorScheme.primary.withOpacity(.1),
      focusColor: colorScheme.primary.withOpacity(.1),
      // accentColor: secondary,
      scaffoldBackgroundColor: colorScheme.background,
      appBarTheme: AppBarTheme(
        backgroundColor: colorScheme.background,
        elevation: 0,
        titleTextStyle: TextStyle(
            fontFamily: 'GoogleSans',
            color: colorScheme.onBackground,
            fontSize: 23,
            fontWeight: FontWeight.normal),
        iconTheme: IconThemeData(color: colorScheme.onBackground),
      ),
      listTileTheme: ListTileThemeData(
        iconColor: colorScheme.primary,
      ),
      textTheme: TextTheme(
        headline1: TextStyle(
          fontFamily: 'GoogleSansBold',
          color: colorScheme.onBackground,
          fontSize: 35,
          fontWeight: FontWeight.bold,
        ),
        headline2: TextStyle(
          fontFamily: 'GoogleSans',
          color: colorScheme.onBackground,
          fontSize: 35,
          fontWeight: FontWeight.normal,
        ),
        headline3: TextStyle(
          fontFamily: 'GoogleSansBold',
          color: colorScheme.onBackground,
          fontSize: 30,
          fontWeight: FontWeight.bold,
        ),
        headline4: TextStyle(
          fontFamily: 'GoogleSans',
          color: colorScheme.onBackground,
          fontSize: 30,
          fontWeight: FontWeight.normal,
        ),
        headline5: TextStyle(
          fontFamily: 'GoogleSansBold',
          color: colorScheme.onBackground,
          fontSize: 25,
          fontWeight: FontWeight.bold,
        ),
        headline6: TextStyle(
          fontFamily: 'GoogleSans',
          color: colorScheme.onBackground,
          fontSize: 25,
          fontWeight: FontWeight.normal,
        ),
        subtitle1: TextStyle(
          fontFamily: 'GoogleSansBold',
          color: colorScheme.onBackground,
          fontSize: 16,
          fontWeight: FontWeight.bold,
        ),
        subtitle2: TextStyle(
          fontFamily: 'GoogleSans',
          color: colorScheme.onBackground,
          fontSize: 16,
          fontWeight: FontWeight.normal,
        ),
        bodyText1: TextStyle(
          fontFamily: 'GoogleSansTextBold',
          color: colorScheme.onBackground,
          fontSize: 14,
          letterSpacing: .8,
          fontWeight: FontWeight.bold,
        ),
        bodyText2: TextStyle(
          fontFamily: 'GoogleSansText',
          color: colorScheme.onBackground,
          fontSize: 14,
          fontWeight: FontWeight.normal,
        ),
        caption: TextStyle(
          fontFamily: 'GoogleSansText',
          color: colorScheme.onBackground,
          fontSize: 12,
          fontWeight: FontWeight.normal,
        ),
        button: TextStyle(
          fontFamily: 'GoogleSansBold',
          color: colorScheme.onBackground,
          fontSize: 14,
          fontWeight: FontWeight.bold,
        ),
        overline: TextStyle(
            fontFamily: 'GoogleSansText',
            color: colorScheme.onBackground,
            fontSize: 10,
            fontWeight: FontWeight.bold,
            letterSpacing: 1.5),
      ),
    );
  }
}
